---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ykwapi.cn.hrimfaxi
  resources:
  - ykwapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ykwapi.cn.hrimfaxi
  resources:
  - ykwapplications/finalizers
  verbs:
  - update
- apiGroups:
  - ykwapi.cn.hrimfaxi
  resources:
  - ykwapplications/status
  verbs:
  - get
  - patch
  - update
