# permissions for end users to edit ykwapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ykwapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ykw-operator
    app.kubernetes.io/part-of: ykw-operator
    app.kubernetes.io/managed-by: kustomize
  name: ykwapplication-editor-role
rules:
- apiGroups:
  - ykwapi.cn.hrimfaxi
  resources:
  - ykwapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ykwapi.cn.hrimfaxi
  resources:
  - ykwapplications/status
  verbs:
  - get
