apiVersion: ykwapi.cn.hrimfaxi/v1
kind: YkwApplication
metadata:
  labels:
    app.kubernetes.io/name: ykwapplication
    app.kubernetes.io/instance: ykwapplication-sample
    app.kubernetes.io/part-of: ykw-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ykw-operator
  name: ykwapplication-sample
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
  # TODO(user): Add fields here
